adding unit tests to install script

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -23,6 +23,18 @@ cd `dirname $0`
 . ./Configuration
 
 #
+# Run unit tests
+#
+cd unittest
+./all_tests.csh
+if [ $? -ne 0 ]
+then
+    echo "Unit tests failed"
+    exit 1
+fi
+cd ..
+
+#
 # Verify the arguments to the script.
 #
 if [ $# -ne 1 ]
